language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=check
      dist: xenial
    - python: 3.7
      env: TOXENV=docs
      dist: xenial

    - python: 3.7
      env: TOXENV=unit-py37
      dist: xenial
  allow_failures:
    - python: 3.7
      env: TOXENV=check-extra
      dist: xenial

install:
  - pip install tox

script:
  - export TOX_SKIP_MISSING_INTERPRETERS="False"
  - tox
